abhishek_dbt_learn:
  outputs:
    dev:
      catalog: dbt_tutorials_dev
      host: dbc-4059fbe6-f211.cloud.databricks.com
      http_path: /sql/1.0/warehouses/1ade2d42f17eb7ec
      schema: default
      threads: 1
      token: dapi1242963b7ad6be4bda1db51ff5fbb4c1
      type: databricks
  target: dev
